travis:
  secure:
    BINSTAR_TOKEN: ClbZZDqt1I/iNOKRyiom6PTcnbqGcAuYHnUFWqe8f8T4U/tWfdU9UIO7pDbHZfd88/TKr/UOnMpiEDeNF1qWlH43pi3LMTwgywF9sVpGFeIOCfr0htlCbtdncpXlXJFq1ROQvarzJGV5oR5NNerskmBeDtVJuFp0LJE2ZiCTgGUBtt+6Ri6VvXVTmEvRqo9OKbVzA8phiCrF985zV1TYIDRXXSONcHs+q34exVR9ddG6b6egpomYfsZVq0L7TG9Bus5PrdYSBSVnv4bkI2/zmq5O8v/SeT4oeQljwLfYHlJH5+guALFCkvfAjEIaq2dyIWbNnBjBYSiCQrDPq9+iuDh/irvysz6HdZrTCAkZPX7R+q4ZqP+UeV6u6h9LwSicV1hfZTHdfLnXi+9wHlkzc1h6Rv/Cm4X4wQBTgs+kXaxTyMUVnvoP2OxPSdxj20NtxqOevQxt7qgV42XBsFtCkSjbOuUmCEuTAZinmxW+4RYJI8dgStdsVOykeXv06hG6mmlK69kgG9uecLuBbysUL4bYzwPMla3w34L8lblPmiUyre41AJD6ofsH9FIfZas/8sTGnle5XR1LnhB1S3MPh1JTsPKHo1xWSjz+YC4JUTegJ2p7B6U8ivwqSDSHEcey2dUoZV3F6ZULhlehuvwtJZZgEddZ8V/P9Y5VYe1Gx6w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
